# Generated by Django 3.2.5 on 2021-07-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('discriminator', models.CharField(max_length=5)),
                ('avatar', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('verified', models.BooleanField()),
                ('registered', models.BooleanField()),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
