# Generated by Django 3.2.5 on 2022-10-13 02:33

from django.db import migrations, models
import django.utils.timezone
from django.utils import timezone
from datetime import date, datetime

def date_to_datetime(apps, schema_editor):
    User = apps.get_model('discordauth', 'User')
    for user in User.objects.all():
        user.created_at = datetime.combine(user.date_created, datetime.min.time())
        user._last_saved = datetime.combine(user.last_saved, datetime.min.time())
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('discordauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_last_saved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
	migrations.RunPython(date_to_datetime)
    ]
