# Generated by Django 3.2.5 on 2022-10-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordauth', '0002_auto_20221013_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_saved',
        ),
    ]
