# Generated by Django 4.2 on 2024-07-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordauth', '0007_alter_user_discriminator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discriminator',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
