# Generated by Django 3.2.5 on 2021-10-26 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceStatsV5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolled', models.IntegerField(default=0)),
                ('total_fail', models.IntegerField(default=0)),
                ('bestial_fail', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('messy_critical', models.IntegerField(default=0)),
                ('reroll', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiceStats20th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolled', models.IntegerField(default=0)),
                ('botched', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
