# Generated by Django 3.2.5 on 2022-06-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0002_auto_20220601_1324'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeTracker20th',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message_id', models.BigIntegerField(unique=True)),
                ('phase', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=0)),
                ('lockout', models.BooleanField(default=False)),
                ('last_updated', models.DateField(auto_now=True)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicle.chronicle')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rolled', models.BooleanField(default=False)),
                ('pool', models.IntegerField(default=0)),
                ('mod', models.IntegerField(default=0)),
                ('init', models.IntegerField(default=0)),
                ('declared', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicle.member')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='bot.initiativetracker20th')),
            ],
            options={
                'unique_together': {('tracker', 'member', 'name')},
            },
        ),
    ]
