# Generated by Django 3.2.5 on 2023-04-06 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0003_auto_20230330_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('used', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'command', 'bot')},
            },
        ),
        migrations.RemoveField(
            model_name='dicestatsv5',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiceStats20th',
        ),
        migrations.DeleteModel(
            name='DiceStatsV5',
        ),
    ]
