# Generated by Django 3.2.5 on 2021-10-26 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_guild', models.BooleanField(default=True)),
                ('guild_member_count', models.IntegerField(default=0)),
                ('icon_url', models.URLField(blank=True)),
                ('tracker_channel', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorytellerRole',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicle.chronicle')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('last_updated', models.DateField(auto_now=True)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicle.chronicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chronicle', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chronicle',
            name='members',
            field=models.ManyToManyField(related_name='chronicles', through='chronicle.Member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chronicle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chronicle',
            name='storytellers',
            field=models.ManyToManyField(related_name='storytellers_chronicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
