# Generated by Django 3.2.5 on 2022-10-13 02:33

from django.db import migrations, models
import django.utils.timezone
from datetime import date, datetime

def date_to_datetime(apps, schema_editor):
    User = apps.get_model('chronicle', 'Chronicle')
    for user in User.objects.all():
        user._last_updated = datetime.combine(user.last_updated, datetime.min.time())
        user.save()

def date_to_datetime_member(apps, schema_editor):
    User = apps.get_model('chronicle', 'Member')
    for user in User.objects.all():
        user._last_updated = datetime.combine(user.last_updated, datetime.min.time())
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0002_auto_20220601_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='display_name',
        ),
        migrations.AddField(
            model_name='chronicle',
            name='_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chronicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
	migrations.RunPython(date_to_datetime),
	migrations.RunPython(date_to_datetime_member)
    ]
