# Generated by Django 3.2.5 on 2022-10-13 03:14

from django.db import migrations
from datetime import date, datetime

def date_to_datetime(apps, schema_editor):
    User = apps.get_model('chronicle', 'Chronicle')
    for user in User.objects.all():
        user._last_updated = datetime.combine(user.last_updated, datetime.min.time())
        user.save()

def date_to_datetime_member(apps, schema_editor):
    User = apps.get_model('chronicle', 'Member')
    for user in User.objects.all():
        user._last_updated = datetime.combine(user.last_updated, datetime.min.time())
        user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_auto_20221013_0233'),
    ]

    operations = [
	migrations.RunPython(date_to_datetime),
	migrations.RunPython(date_to_datetime_member)
    ]
