# Generated by Django 3.2.5 on 2022-10-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0004_remove_member_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicle',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_updated',
        ),
    ]
