# Generated by Django 3.2.5 on 2022-10-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0005_auto_20221013_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chronicle',
            old_name='_last_updated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='_last_updated',
            new_name='last_updated',
        ),
    ]
