# Generated by Django 3.2.5 on 2023-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20230330_0338'),
        ('chronicle', '0006_auto_20221013_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicle',
            name='bot',
            field=models.ManyToManyField(related_name='chronicles', to='bot.Bot'),
        ),
        migrations.AddField(
            model_name='chronicle',
            name='owner_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chronicle',
            name='shard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
