# Generated by Django 4.2 on 2023-05-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0006_character_data'),
        ('chronicle', '0008_auto_20230404_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_auto_hunger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='default_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_defaults', to='haven.character'),
        ),
    ]
