# Generated by Django 4.2.16 on 2025-07-21 12:00

from django.db import migrations, models
from django.contrib.auth import get_user_model

User = get_user_model()


def increment_supporter_tiers(apps, schema_editor):
    """
    Increment supporter tier by 1 for all users with supporter > 0.
    This is due to the addition of the new 'mortal' tier as level 1,
    which shifts all existing tiers up by one level.
    """

    # Update all users with supporter > 0 to increment by 1
    User.objects.filter(supporter__gt=0).update(supporter=models.F("supporter") + 1)


def reverse_increment_supporter_tiers(apps, schema_editor):
    """
    Reverse the supporter tier increment by decrementing by 1
    for all users with supporter > 1.
    """

    # Reverse the increment for all users with supporter > 1
    User.objects.filter(supporter__gt=1).update(supporter=models.F("supporter") - 1)


class Migration(migrations.Migration):

    dependencies = [
        ("discordauth", "0008_alter_user_discriminator"),
    ]

    operations = [
        migrations.RunPython(
            increment_supporter_tiers,
            reverse_increment_supporter_tiers,
        ),
    ]
