blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.com/invite/p82yc8sKx2
    about: Join our Discord server for real-time discussions.
  - name: Discussions
    url: https://github.com/Mirai-Miki/realmofdarkness.app/discussions
    about: Please ask and answer questions here.
