# Generated by Django 3.2.5 on 2022-08-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter5th',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='haven.character')),
                ('despair', models.BooleanField(default=False)),
            ],
        ),
    ]
