# Generated by Django 3.2.5 on 2022-10-13 02:33

from django.db import migrations, models
import django.utils.timezone
from datetime import date, datetime

def date_to_datetime(apps, schema_editor):
    Character = apps.get_model('haven', 'Character')
    for user in Character.objects.all():
        user.created_at = datetime.combine(user.date_created, datetime.min.time())
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0002_hunter5th'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splat',
            name='game',
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='theme',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AddField(
            model_name='moralityinfo',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moralityinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moralityinfo',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='Colour',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
	migrations.RunPython(date_to_datetime)
    ]
