# Generated by Django 4.2 on 2023-10-23 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0007_character5th_customclan_custompredatortype_morals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vampire5th',
            name='hunting_roll',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vampire5th',
            name='resonance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vampire5th',
            name='blood_potency',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vampire5th',
            name='generation',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='vampire5th',
            name='humanity',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vampire5th',
            name='hunger',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vampire5th',
            name='stains',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
