# Generated by Django 4.2 on 2023-11-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0011_character_age_character_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp_spends',
            field=models.JSONField(default=list),
        ),
    ]
