# Generated by Django 4.2 on 2024-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0013_remove_character5th_chronicle_tenets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character5th',
            name='backgrounds',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='character5th',
            name='flaws',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='character5th',
            name='haven',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='character5th',
            name='loresheets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='character5th',
            name='merits',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Morals',
        ),
    ]
