# Generated by Django 4.2 on 2024-02-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0014_character5th_backgrounds_character5th_flaws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character5th',
            name='haven_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='character5th',
            name='haven_location',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='character5th',
            name='haven_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
