# Generated by Django 4.2 on 2024-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0016_remove_character_faceclaim_character_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='st_lock',
            field=models.BooleanField(default=False),
        ),
    ]
