# Generated by Django 4.2 on 2024-07-06 03:17

import django.core.validators
from django.db import migrations, models

def set_splat_new(apps, schema_editor):
    Vampire5th = apps.get_model("haven", "Vampire5th")
    Vampire5th.objects.all().update(splat_new="vampire5th")

class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0017_character_st_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='werewolf5th',
            name='crinos',
        ),
        migrations.AddField(
            model_name='character',
            name='splat_new',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='werewolf5th',
            name='form',
            field=models.CharField(choices=[('Homid', 'Homid'), ('Glabro', 'Glabro'), ('Crinos', 'Chrinos'), ('Hispo', 'Hispo'), ('Lupus', 'Lupus')], default='Homid', max_length=15),
        ),
        migrations.AddField(
            model_name='werewolf5th',
            name='harano',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='werewolf5th',
            name='hauglosk',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RunPython(set_splat_new),
    ]
