# Generated by Django 5.1.6 on 2025-03-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0018_remove_werewolf5th_crinos_character_splat_new_and_more'),
    ]

    operations = [
        # Rename Hunter5th model to DespairModal
        migrations.RenameModel(
            old_name="Hunter5th",
            new_name="DespairModal",
        ),
        # Rename splat field to splat_old
        migrations.RenameField(
            model_name="character",
            old_name="splat",
            new_name="splat_old",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="appearance",
            new_name="appearance_description",
        ),
    ]
