# Generated by Django 5.2.3 on 2025-06-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0020_character20th_ghoul5th_human5th_hunter5th_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vampire5th',
            name='predator_type',
            field=models.CharField(blank=True, choices=[('Custom', 'Custom'), ('Alleycat', 'Alleycat'), ('Blood Leech', 'Blood Leech'), ('Bagger', 'Bagger'), ('Cleaver', 'Cleaver'), ('Consensualist', 'Consensualist'), ('Farmer', 'Farmer'), ('Osiris', 'Osiris'), ('Sandman', 'Sandman'), ('Scene Queen', 'Scene Queen'), ('Siren', 'Siren'), ('Extortionist', 'Extortionist'), ('Graverobber', 'Graverobber'), ('Roadside Killer', 'Roadside Killer'), ('Grim Reaper', 'Grim Reaper'), ('Montero', 'Montero'), ('Pursuer', 'Pursuer'), ('Trapdoor', 'Trapdoor'), ('Tithe Collector', 'Tithe Collector')], max_length=20),
        ),
    ]
