# Generated by Django 5.2.3 on 2025-07-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0021_alter_vampire5th_predator_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demontf',
            old_name='torment_total',
            new_name='torment_permanent',
        ),
        migrations.RenameField(
            model_name='demontf',
            old_name='torment_current',
            new_name='torment_temporary',
        ),
    ]
