# Generated by Django 5.1.6 on 2025-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20230406_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativetracker20th',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
