# Generated by Django 3.2.5 on 2022-10-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0003_auto_20221013_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='date_created',
        ),
    ]
