# Generated by Django 3.2.5 on 2023-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0004_remove_character_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
