# Generated by Django 3.2.5 on 2023-03-30 03:46

from django.db import migrations
def updateParadox(apps, scheme_editor):
    model = apps.get_model('haven', 'Trackable')
    para = model.objects.filter(slug='quint_paradox')
    for x in para:
        x.total = 0
        x.current = 0
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0005_character_data'),
    ]

    operations = [
        migrations.RunPython(updateParadox),
    ]
