# Generated by Django 4.2 on 2023-11-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0012_character_exp_spends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character5th',
            name='chronicle_tenets',
        ),
        migrations.AddField(
            model_name='character',
            name='notes2',
            field=models.TextField(blank=True, max_length=6000),
        ),
        migrations.AddField(
            model_name='character5th',
            name='convictions',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='character5th',
            name='tenets',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='character5th',
            name='touchstones',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
