# Generated by Django 4.2 on 2024-02-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0015_character5th_haven_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='faceclaim',
        ),
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='char_avatars/'),
        ),
    ]
