# Generated by Django 3.2.5 on 2022-06-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicle',
            name='guild_member_count',
        ),
        migrations.RemoveField(
            model_name='chronicle',
            name='owner',
        ),
    ]
