# Generated by Django 3.2.5 on 2023-04-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0007_auto_20230330_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicle',
            name='storytellers',
        ),
        migrations.AddField(
            model_name='member',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='storyteller',
            field=models.BooleanField(default=False),
        ),
    ]
